/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteInviteIdRouteImport } from './routes/invite.$inviteId'
import { Route as GroupsGroupIdRouteImport } from './routes/groups.$groupId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as GroupsGroupIdMembersRouteImport } from './routes/groups.$groupId.members'
import { Route as GroupsGroupIdAddRouteImport } from './routes/groups.$groupId.add'
import { Route as GroupsGroupIdTripsTripIdRouteImport } from './routes/groups.$groupId.trips.$tripId'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviteIdRoute = InviteInviteIdRouteImport.update({
  id: '/invite/$inviteId',
  path: '/invite/$inviteId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdMembersRoute = GroupsGroupIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdAddRoute = GroupsGroupIdAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdTripsTripIdRoute =
  GroupsGroupIdTripsTripIdRouteImport.update({
    id: '/trips/$tripId',
    path: '/trips/$tripId',
    getParentRoute: () => GroupsGroupIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/groups/$groupId/add': typeof GroupsGroupIdAddRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/trips/$tripId': typeof GroupsGroupIdTripsTripIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/groups/$groupId/add': typeof GroupsGroupIdAddRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/trips/$tripId': typeof GroupsGroupIdTripsTripIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/invite/$inviteId': typeof InviteInviteIdRoute
  '/groups/$groupId/add': typeof GroupsGroupIdAddRoute
  '/groups/$groupId/members': typeof GroupsGroupIdMembersRoute
  '/groups/$groupId/trips/$tripId': typeof GroupsGroupIdTripsTripIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/groups/$groupId'
    | '/invite/$inviteId'
    | '/groups/$groupId/add'
    | '/groups/$groupId/members'
    | '/groups/$groupId/trips/$tripId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/groups/$groupId'
    | '/invite/$inviteId'
    | '/groups/$groupId/add'
    | '/groups/$groupId/members'
    | '/groups/$groupId/trips/$tripId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/auth/callback'
    | '/groups/$groupId'
    | '/invite/$inviteId'
    | '/groups/$groupId/add'
    | '/groups/$groupId/members'
    | '/groups/$groupId/trips/$tripId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  InviteInviteIdRoute: typeof InviteInviteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviteId': {
      id: '/invite/$inviteId'
      path: '/invite/$inviteId'
      fullPath: '/invite/$inviteId'
      preLoaderRoute: typeof InviteInviteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/members': {
      id: '/groups/$groupId/members'
      path: '/members'
      fullPath: '/groups/$groupId/members'
      preLoaderRoute: typeof GroupsGroupIdMembersRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/add': {
      id: '/groups/$groupId/add'
      path: '/add'
      fullPath: '/groups/$groupId/add'
      preLoaderRoute: typeof GroupsGroupIdAddRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/trips/$tripId': {
      id: '/groups/$groupId/trips/$tripId'
      path: '/trips/$tripId'
      fullPath: '/groups/$groupId/trips/$tripId'
      preLoaderRoute: typeof GroupsGroupIdTripsTripIdRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdAddRoute: typeof GroupsGroupIdAddRoute
  GroupsGroupIdMembersRoute: typeof GroupsGroupIdMembersRoute
  GroupsGroupIdTripsTripIdRoute: typeof GroupsGroupIdTripsTripIdRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdAddRoute: GroupsGroupIdAddRoute,
  GroupsGroupIdMembersRoute: GroupsGroupIdMembersRoute,
  GroupsGroupIdTripsTripIdRoute: GroupsGroupIdTripsTripIdRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  InviteInviteIdRoute: InviteInviteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
