/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List groups for current user */
        get: operations["list-groups"];
        put?: never;
        /** Create a group */
        post: operations["create-group"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get group details */
        get: operations["get-group"];
        /** Update group name */
        put: operations["update-group"];
        post?: never;
        /** Delete a group */
        delete: operations["delete-group"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List API keys for a group */
        get: operations["list-api-keys"];
        put?: never;
        /** Create an API key for a group */
        post: operations["create-api-key"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/api-keys/{keyID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revoke an API key for a group */
        delete: operations["revoke-api-key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List categories for a group */
        get: operations["list-categories"];
        put?: never;
        /** Create a category */
        post: operations["create-category"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/categories/{categoryID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a category */
        delete: operations["delete-category"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List active invites for a group */
        get: operations["list-invites"];
        put?: never;
        /** Create an invite link for a group */
        post: operations["create-invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/invites/{inviteID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete an invite */
        delete: operations["delete-invite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List group members */
        get: operations["list-members"];
        put?: never;
        /** Add a member to group */
        post: operations["add-member"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/members/{userID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update nickname for a group member */
        put: operations["update-member-nickname"];
        post?: never;
        /** Remove a member from group */
        delete: operations["remove-member"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/members/{userID}/merge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Admin: merge a ghost user into a real user */
        post: operations["admin-merge-ghost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/purchases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List purchases for a group */
        get: operations["list-purchases"];
        put?: never;
        /** Create a purchase */
        post: operations["create-purchase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/purchases/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create multiple purchases */
        post: operations["create-purchases-bulk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/purchases/{purchaseID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a purchase */
        put: operations["update-purchase"];
        post?: never;
        /** Delete a purchase */
        delete: operations["delete-purchase"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/purchases/{purchaseID}/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a receipt */
        post: operations["upload-receipt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/settlements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calculate settlements for a group */
        get: operations["calculate-settlements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/settlements/{settlementID}/paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark a settlement as paid */
        post: operations["mark-settlement-paid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all trips in a group */
        get: operations["list-trips"];
        put?: never;
        /** Create a trip/event in a group */
        post: operations["create-trip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupID}/trips/{tripID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a trip with its purchases */
        get: operations["get-trip"];
        /** Update a trip */
        put: operations["update-trip"];
        post?: never;
        /** Delete a trip (purchases become unassigned) */
        delete: operations["delete-trip"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/invites/{inviteID}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept an invite and join the group */
        post: operations["accept-invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/ghost": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a ghost user */
        post: operations["create-ghost-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userID}/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Claim a ghost user account */
        post: operations["claim-ghost-user"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        APIKeyRow: {
            actingAsUserId: string;
            /** Format: date-time */
            createdAt: string;
            createdByUserId: string;
            groupId: string;
            id: string;
            label: string;
            /** Format: date-time */
            lastUsedAt?: string;
            /** Format: date-time */
            revokedAt?: string;
        };
        AcceptInviteOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/AcceptInviteOutputBody.json
             */
            readonly $schema?: string;
            groupId: string;
            groupName: string;
        };
        AddMemberInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/AddMemberInputBody.json
             */
            readonly $schema?: string;
            /** @description User ID to add */
            userId: string;
        };
        AdminClaimGhostInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/AdminClaimGhostInputBody.json
             */
            readonly $schema?: string;
            /** @description Real user ID to merge ghost into */
            targetUserId: string;
        };
        Assignment: {
            /** Format: int64 */
            customShareCents?: number;
            id: string;
            purchaseId: string;
            userId: string;
        };
        BulkPurchaseOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/BulkPurchaseOutputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Number of purchases created
             */
            count: number;
            /** @description Created purchase IDs */
            ids: string[] | null;
        };
        Category: {
            groupId: string;
            id: string;
            name: string;
        };
        CreateAPIKeyInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateAPIKeyInputBody.json
             */
            readonly $schema?: string;
            /** @description User ID this key acts as */
            actingAsUserId: string;
            /** @description Human-readable label */
            label: string;
        };
        CreateAPIKeyOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateAPIKeyOutputBody.json
             */
            readonly $schema?: string;
            actingAsUserId: string;
            createdAt: string;
            createdByUserId: string;
            id: string;
            label: string;
            token: string;
        };
        CreateCategoryInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateCategoryInputBody.json
             */
            readonly $schema?: string;
            /** @description Category name */
            name: string;
        };
        CreateCategoryOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateCategoryOutputBody.json
             */
            readonly $schema?: string;
            /** @description Created category ID */
            id: string;
        };
        CreateGhostUserInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateGhostUserInputBody.json
             */
            readonly $schema?: string;
            /** @description Ghost user name */
            name: string;
        };
        CreateGhostUserOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateGhostUserOutputBody.json
             */
            readonly $schema?: string;
            /** @description Created ghost user ID */
            id: string;
        };
        CreateGroupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateGroupInputBody.json
             */
            readonly $schema?: string;
            /** @description Group name */
            name: string;
        };
        CreateGroupOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateGroupOutputBody.json
             */
            readonly $schema?: string;
            /** @description Created group ID */
            id: string;
        };
        CreateInviteInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateInviteInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Expiry in hours (null = never)
             */
            expiresIn?: number;
            /**
             * Format: int64
             * @description Max number of uses (null = unlimited)
             */
            maxUses?: number;
        };
        CreatePurchaseOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreatePurchaseOutputBody.json
             */
            readonly $schema?: string;
            /** @description Created purchase ID */
            id: string;
        };
        CreateTripInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/CreateTripInputBody.json
             */
            readonly $schema?: string;
            /** @description Optional description */
            description?: string;
            /** @description Trip name */
            name: string;
            /** @description Date of trip (YYYY-MM-DD) */
            tripDate?: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FormFile: {
            ContentType: string;
            Filename: string;
            IsSet: boolean;
            /** Format: int64 */
            Size: number;
        };
        Group: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/Group.json
             */
            readonly $schema?: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            id: string;
            name: string;
        };
        Invite: {
            createdAt: string;
            createdBy: string;
            expiresAt?: string;
            groupId: string;
            id: string;
            /** Format: int64 */
            maxUses?: number;
            /** Format: int64 */
            useCount: number;
        };
        InviteOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/InviteOutputBody.json
             */
            readonly $schema?: string;
            createdAt: string;
            expiresAt?: string;
            groupId: string;
            /** @description Invite ID (use as token in link) */
            id: string;
            /** Format: int64 */
            maxUses?: number;
            /** Format: int64 */
            useCount: number;
        };
        Item: {
            /**
             * Format: int64
             * @description Amount in cents (negative for refunds)
             */
            amountCents: number;
            /** @description User IDs to split between */
            assignedTo: string[] | null;
            /** @description Category ID */
            categoryId?: string;
            /** @description Purchase description */
            description: string;
            /** @description User who paid */
            paidByUserId: string;
            /** @description Date of purchase (YYYY-MM-DD) */
            purchasedAt?: string;
            /** @description Trip ID */
            tripId?: string;
        };
        MemberWithUser: {
            avatarUrl?: string;
            email?: string;
            id: string;
            isGhost: boolean;
            name: string;
            nickname?: string;
            originalName: string;
            role: string;
        };
        PurchaseInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/PurchaseInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Amount in cents (negative for refunds)
             */
            amountCents: number;
            /** @description User IDs to split between */
            assignedTo: string[] | null;
            /** @description Category ID */
            categoryId?: string;
            /** @description Purchase description */
            description: string;
            /** @description User who paid */
            paidByUserId: string;
            /** @description Date of purchase (YYYY-MM-DD) */
            purchasedAt?: string;
            /** @description Trip ID */
            tripId?: string;
        };
        PurchaseWithAssignments: {
            /** Format: int64 */
            amountCents: number;
            assignments: components["schemas"]["Assignment"][] | null;
            categoryId?: string;
            /** Format: date-time */
            createdAt: string;
            createdBy: string;
            description: string;
            groupId: string;
            id: string;
            paidByUserId: string;
            purchasedAt: string;
            receiptUrl?: string;
            tripId?: string;
        };
        SettlementResponse: {
            /** Format: int64 */
            amountCents: number;
            fromUserId: string;
            toUserId: string;
        };
        StatusOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/StatusOutputBody.json
             */
            readonly $schema?: string;
            status: string;
        };
        Trip: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/Trip.json
             */
            readonly $schema?: string;
            createdAt: string;
            createdBy: string;
            description?: string;
            groupId: string;
            id: string;
            name: string;
            tripDate: string;
        };
        TripWithTotal: {
            createdAt: string;
            createdBy: string;
            description?: string;
            groupId: string;
            id: string;
            name: string;
            /** Format: int64 */
            purchaseCount: number;
            /** Format: int64 */
            totalCents: number;
            tripDate: string;
        };
        UpdateGroupInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/UpdateGroupInputBody.json
             */
            readonly $schema?: string;
            /** @description New group name */
            name: string;
        };
        UpdateMemberNicknameInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/UpdateMemberNicknameInputBody.json
             */
            readonly $schema?: string;
            /** @description Nickname for this group, empty clears it */
            nickname: string;
        };
        UpdatePurchaseInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/UpdatePurchaseInputBody.json
             */
            readonly $schema?: string;
            /**
             * Format: int64
             * @description Amount in cents
             */
            amountCents: number;
            /** @description User IDs to split between */
            assignedTo: string[] | null;
            /** @description Category ID */
            categoryId?: string;
            /** @description Purchase description */
            description: string;
            /** @description User who paid */
            paidByUserId: string;
            /** @description Date of purchase (YYYY-MM-DD) */
            purchasedAt?: string;
            /** @description Trip ID */
            tripId?: string;
        };
        UpdateTripInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/UpdateTripInputBody.json
             */
            readonly $schema?: string;
            /** @description Optional description */
            description?: string;
            /** @description Trip name */
            name: string;
            /** @description Date of trip (YYYY-MM-DD) */
            tripDate?: string;
        };
        UploadReceiptOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/UploadReceiptOutputBody.json
             */
            readonly $schema?: string;
            /** @description URL of the uploaded receipt */
            receiptUrl: string;
        };
        User: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://api.financensor.stammkneipe.dev/schemas/User.json
             */
            readonly $schema?: string;
            avatarUrl?: string;
            /** Format: date-time */
            createdAt: string;
            email?: string;
            id: string;
            isGhost: boolean;
            name: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type SchemaApiKeyRow = components['schemas']['APIKeyRow'];
export type SchemaAcceptInviteOutputBody = components['schemas']['AcceptInviteOutputBody'];
export type SchemaAddMemberInputBody = components['schemas']['AddMemberInputBody'];
export type SchemaAdminClaimGhostInputBody = components['schemas']['AdminClaimGhostInputBody'];
export type SchemaAssignment = components['schemas']['Assignment'];
export type SchemaBulkPurchaseOutputBody = components['schemas']['BulkPurchaseOutputBody'];
export type SchemaCategory = components['schemas']['Category'];
export type SchemaCreateApiKeyInputBody = components['schemas']['CreateAPIKeyInputBody'];
export type SchemaCreateApiKeyOutputBody = components['schemas']['CreateAPIKeyOutputBody'];
export type SchemaCreateCategoryInputBody = components['schemas']['CreateCategoryInputBody'];
export type SchemaCreateCategoryOutputBody = components['schemas']['CreateCategoryOutputBody'];
export type SchemaCreateGhostUserInputBody = components['schemas']['CreateGhostUserInputBody'];
export type SchemaCreateGhostUserOutputBody = components['schemas']['CreateGhostUserOutputBody'];
export type SchemaCreateGroupInputBody = components['schemas']['CreateGroupInputBody'];
export type SchemaCreateGroupOutputBody = components['schemas']['CreateGroupOutputBody'];
export type SchemaCreateInviteInputBody = components['schemas']['CreateInviteInputBody'];
export type SchemaCreatePurchaseOutputBody = components['schemas']['CreatePurchaseOutputBody'];
export type SchemaCreateTripInputBody = components['schemas']['CreateTripInputBody'];
export type SchemaErrorDetail = components['schemas']['ErrorDetail'];
export type SchemaErrorModel = components['schemas']['ErrorModel'];
export type SchemaFormFile = components['schemas']['FormFile'];
export type SchemaGroup = components['schemas']['Group'];
export type SchemaInvite = components['schemas']['Invite'];
export type SchemaInviteOutputBody = components['schemas']['InviteOutputBody'];
export type SchemaItem = components['schemas']['Item'];
export type SchemaMemberWithUser = components['schemas']['MemberWithUser'];
export type SchemaPurchaseInputBody = components['schemas']['PurchaseInputBody'];
export type SchemaPurchaseWithAssignments = components['schemas']['PurchaseWithAssignments'];
export type SchemaSettlementResponse = components['schemas']['SettlementResponse'];
export type SchemaStatusOutputBody = components['schemas']['StatusOutputBody'];
export type SchemaTrip = components['schemas']['Trip'];
export type SchemaTripWithTotal = components['schemas']['TripWithTotal'];
export type SchemaUpdateGroupInputBody = components['schemas']['UpdateGroupInputBody'];
export type SchemaUpdateMemberNicknameInputBody = components['schemas']['UpdateMemberNicknameInputBody'];
export type SchemaUpdatePurchaseInputBody = components['schemas']['UpdatePurchaseInputBody'];
export type SchemaUpdateTripInputBody = components['schemas']['UpdateTripInputBody'];
export type SchemaUploadReceiptOutputBody = components['schemas']['UploadReceiptOutputBody'];
export type SchemaUser = components['schemas']['User'];
export type $defs = Record<string, never>;
export interface operations {
    "list-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-group": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGroupInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGroupOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-group": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Group"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-group": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-group": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["APIKeyRow"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAPIKeyInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAPIKeyOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "revoke-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description API key ID */
                keyID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-category": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCategoryInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateCategoryOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-category": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Category ID */
                categoryID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-invites": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInviteInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InviteOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Invite ID */
                inviteID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberWithUser"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "add-member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-member-nickname": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description User ID to update */
                userID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberNicknameInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "remove-member": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description User ID to remove */
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "admin-merge-ghost": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Ghost user ID to merge */
                userID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminClaimGhostInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-purchases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurchaseWithAssignments"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-purchase": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PurchaseInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatePurchaseOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-purchases-bulk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Item"][] | null;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkPurchaseOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-purchase": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Purchase ID */
                purchaseID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePurchaseInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-purchase": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Purchase ID */
                purchaseID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "upload-receipt": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Purchase ID */
                purchaseID: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    receipt: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadReceiptOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "calculate-settlements": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettlementResponse"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "mark-settlement-paid": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Settlement ID */
                settlementID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-trips": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripWithTotal"][] | null;
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTripInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Trip ID */
                tripID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Trip ID */
                tripID: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTripInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "delete-trip": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Group ID */
                groupID: string;
                /** @description Trip ID */
                tripID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "accept-invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Invite token */
                inviteID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptInviteOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-ghost-user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGhostUserInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateGhostUserOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "claim-ghost-user": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Ghost user ID to claim */
                userID: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
